### ISSUE TITLE
A10: Course deletion returns 400

### ISSUE THREAD

**Issue by coolnormal23** [masonbesmer/Abet-Course-Assessment-Tool-Frontend#5]
# Expected behavior
The course should be deleted and removed from the table.

# Actual behavior
The course is not deleted, and a 400 is returned that says "see inner exception". Upon printing the inner exception it reads:
```
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
﻿ ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Cannot delete or update a parent row: a foreign key constraint fails (`abetrepo`.`sections`, CONSTRAINT `FK_Sections_Courses_CourseId` FOREIGN KEY (`CourseId`) REFERENCES `courses` (`CourseId`) ON DELETE RESTRICT)
﻿   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
﻿   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
﻿   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
﻿   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
﻿   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
﻿   at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
﻿   at System.Data.Common.DbCommand.ExecuteReader()
﻿   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
﻿   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
﻿   --- End of inner exception stack trace ---
﻿   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
﻿   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
﻿   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
﻿   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
﻿   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
﻿   at MySql.EntityFrameworkCore.Storage.Internal.MySQLExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
﻿   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
﻿   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
﻿   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
﻿   at AbetApi.EFModels.Course.DeleteCourse(String term, Int32 year, String department, String courseNumber)
﻿   at AbetApi.EFModels.Course.DeleteCourse(String term, Int32 year, String department, String courseNumber)
﻿   at AbetApi.Controllers.CourseController.DeleteCourse(String term, Int32 year, String department, String courseNumber)
```

# Proposed solution (if any)
Fix the foreign key constraint

**Comment by Dylan-ER** [comment]
I was able to successfully delete a course without problems. I did not change anything to the code that currently is in the repository.

**Comment by coolnormal23** [comment]
> I was able to successfully delete a course without problems. I did not change anything to the code that currently is in the repository.

That's strange, I'm still getting the same error while fully updated. I even dropped the database and remade it to see if it helped, but still the same "a foreign key constraint fails" and a 400 response. Can you screenshot the requests and response in your browser's development tools?

**Comment by Dylan-ER** [comment]
> That's strange, I'm still getting the same error while fully updated. I even dropped the database and remade it to see if it helped, but still the same "a foreign key constraint fails" and a 400 response. Can you screenshot the requests and response in your browser's development tools?

Here's the requests with me adding and deleting "Learning to beg"

<img width="1280" alt="Screenshot 2023-11-28 174232" src="https://github.com/masonbesmer/Abet-Course-Assessment-Tool-Frontend/assets/65862444/821be23f-ee27-4bd9-99c9-5d4329052c64">
<img width="1280" alt="Screenshot 2023-11-28 174245" src="https://github.com/masonbesmer/Abet-Course-Assessment-Tool-Frontend/assets/65862444/5901d97a-02f2-4078-87e4-e23cf1192b63">
